version: '3.8'

services:
  api:
    build:
      context: ./src
    container_name: api
    environment:
      PORT: 8000
      DATABASE_URL: mysql://bk_store_admin:admin@bk_mysql:3306/bk_store
    ports:
      - '8000:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my_network

  mysql:
    image: mysql:8.4
    container_name: bk_mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      MYSQL_DATABASE: bk_store
      MYSQL_USER: bk_store_admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root_admin
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local

networks:
  my_network:
    driver: bridge
